# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(743, 584)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 743, 22))
        self.menubar.setObjectName("menubar")
        self.menumenu = QtWidgets.QMenu(self.menubar)
        self.menumenu.setObjectName("menumenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCadastrar = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/130manstudent2_100617.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastrar.setIcon(icon)
        self.actionCadastrar.setObjectName("actionCadastrar")
        self.actionAtualizar = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/refresh-page-arrow-button_icon-icons.com_53909.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAtualizar.setIcon(icon1)
        self.actionAtualizar.setObjectName("actionAtualizar")
        self.actionPesquisar = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/systemsearch_104123.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPesquisar.setIcon(icon2)
        self.actionPesquisar.setObjectName("actionPesquisar")
        self.actionExcluir_Aluno = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/dustbin_120823.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExcluir_Aluno.setIcon(icon3)
        self.actionExcluir_Aluno.setObjectName("actionExcluir_Aluno")
        self.menumenu.addAction(self.actionCadastrar)
        self.menumenu.addAction(self.actionAtualizar)
        self.menumenu.addAction(self.actionPesquisar)
        self.menumenu.addAction(self.actionExcluir_Aluno)
        self.menubar.addAction(self.menumenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menumenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionCadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.actionCadastrar.setToolTip(_translate("MainWindow", "Cadastrar alunos no sistema"))
        self.actionAtualizar.setText(_translate("MainWindow", "Atualizar"))
        self.actionAtualizar.setToolTip(_translate("MainWindow", "Atualizar cadastro de alunos"))
        self.actionPesquisar.setText(_translate("MainWindow", "Pesquisar/Enviar Email"))
        self.actionPesquisar.setToolTip(_translate("MainWindow", "Pesquisa alunos no sistema"))
        self.actionExcluir_Aluno.setText(_translate("MainWindow", "Excluir"))
        self.actionExcluir_Aluno.setToolTip(_translate("MainWindow", "Excluir um registro de aluno"))
